apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: online-boutique
resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - redis-cart.yaml
  - shippingservice.yaml
  - shoppingassistantservice.yaml